spring:
  application:
    name: ipa-console-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    # url: jdbc:postgresql://localhost:5432/${PG_DB}
    # username: ${PG_USER}
    # password: ${PG_PASSWORD}
fernandoschilder:
  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 7200000
    n8n-url: ${N8N_URL}
    n8n-apikey: ${N8N_API_KEY}
    cron:
      retrieve-logs: "*/10 * * * * *"