spring:
  application:
    name: ipa-console-backend
  datasource:
    driver-class-name: org.postgresql.Driver
fernandoschilder:
  app:
    front-url: ${FRONT_URL}
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 7200000
    n8n-url: ${N8N_URL}
    n8n-apikey: ${N8N_API_KEY}
    cron:
      retrieve-processes: "0 */5 * * * *"
      retrieve-logs: "0 */1 * * * *"